name: playground

on: [push]

jobs:

  job:
    name: Test container-options configuration
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/nikleberg/quartus-prime:latest
      options: --mac-address=00:ab:ab:ab:ab:ab
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: verify mac address
        run: |
          apt-get -q -y update
          apt-get -q -y install net-tools lsb-core
          ifconfig
          /opt/intelFPGA_lite/21.1/questa_fse/linux_x86_64/mgls/bin/lmhostid
          /opt/intelFPGA_lite/21.1/questa_fse/linux_x86_64/mgls/bin/lmutil lmdiag
