name: playground

on: [push]

jobs:

  job:
    name: Test different action contexts
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: hmarr/debug-action@v2
