name: playground

on: [push]

jobs:

  job:
    name: Test some shell code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: list large files
        run: |
          echo "List of large folders:"
          du -a / | sort -n -r | head -n 10
          echo
