name: playground

on: [push]

jobs:

  job:
    name: Test file glob in sh and bash
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: ls
        run: |
          ls
      
      - name: sh?
        run: |
          echo crash*
          echo "---"
          echo crash*.min

      - name: bash
        shell: bash
        run: |
          echo crash*
          echo "---"
          echo crash*.min
