name: playground

on: [push]

jobs:

  job:
    name: Test file glob in sh and bash
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/nikleberg/dev-base:staging
    steps:

      - name: test
        run: |
          git clone https://github.com/NikLeberg/neorv32_soc.git
          source neorv32_soc/.decvontainer/.env
          ghdl --version
